### ISSUE TITLE
Unable to retrieve DockerHub details

### ISSUE THREAD

**Issue by rastyu** [eysp/public#4]
在portainer/portainer-ce 2.9.1 版中 ，切换到镜像列表时候会出现Unable to retrieve DockerHub details的错误

**Comment by 5dprince** [comment]
解决了吗

**Comment by rastyu** [comment]
![1](https://user-images.githubusercontent.com/48859414/138126712-a5a6df20-fd06-4937-a61d-c817a3b79de5.png)
![2](https://user-images.githubusercontent.com/48859414/138126738-0278a644-0585-4547-8f4f-86822a9cb96d.png)
更新后 这里两个图标显示不出来
