### ISSUE TITLE
arm架构的机子好像不用指定标签拉取镜像

### ISSUE THREAD

**Issue by huangguiniab** [eysp/public#6]
我有两台机子一台arm64的n1和一台x64的电脑，安装portainer的时侯我用的都是这个命令
sudo docker pull portainer/portainer-ce
安装都可以正常使用
好像docker会自己选择架构
我好奇portainer-ce和portainer-ce:linux-arm64有什么区别吗

**Comment by yspcn** [comment]
都可以用就好，arm64主要是给N1等ARM架构设备用的
